// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://atpfhyvdmsxcsfsoozng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF0cGZoeXZkbXN4Y3Nmc29vem5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDkyMDYsImV4cCI6MjA2NzEyNTIwNn0.1j517D029qUFcxQQDe6i8FzSM_NHJZw6zcV3cyplUy4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});